<root xmlns="http://www.w3.org/1999/XSL/Format">
    <layout-master-set>
        <simple-page-master
            margin-bottom="1in"
            margin-left="1.25in"
            margin-right="1.25in"
            margin-top="0.5in"
            master-name="s1-default"
            page-height="297mm"
            page-width="210mm">
            <region-body
                column-count="1"
                column-gap="0.5in"
                margin-left="0mm"
                margin-right="0mm"
                margin-top="36.0pt" />
            <region-before
                extent="10.0pt"
                region-name="xsl-region-before-default" />
        </simple-page-master>
        <page-sequence-master master-name="s1">
            <repeatable-page-master-alternatives>
                <conditional-page-master-reference master-reference="s1-default" />
            </repeatable-page-master-alternatives>
        </page-sequence-master>
    </layout-master-set>
    <page-sequence
        id="section_s1"
        master-reference="s1">
        <static-content flow-name="xsl-region-before-default">
            <block
                font-size="10.0pt"
                line-height="100%"
                space-after="0in"
                space-before="0in">
                <inline>
                    <inline font-family="PMingLiU">工單編號</inline>
                </inline>
            </block>
        </static-content>
        <flow flow-name="xsl-region-body">
            <block font-size="12.0pt">
                <inline>
                    <inline font-family="PMingLiU">保養計畫</inline>
                </inline>
            </block>
            <block font-size="12.0pt">
                <inline>
                    <inline font-family="PMingLiU">開始時間</inline>
                </inline>
            </block>
            <block font-size="12.0pt" />
            <block font-size="12.0pt">
                <fo:table
                    xmlns:fo="http://www.w3.org/1999/XSL/Format"
                    border-bottom-color="#000000"
                    border-bottom-style="solid"
                    border-bottom-width="2.25pt"
                    border-collapse="collapse"
                    border-left-color="#000000"
                    border-left-style="solid"
                    border-left-width="2.25pt"
                    border-right-color="#000000"
                    border-right-style="solid"
                    border-right-width="2.25pt"
                    border-top-color="#000000"
                    border-top-style="solid"
                    border-top-width="2.25pt"
                    display-align="before"
                    start-indent="0in"
                    table-layout="fixed"
                    width="5.74in">
                    <fo:table-column
                        column-number="1"
                        column-width="1.15in" />
                    <fo:table-column
                        column-number="2"
                        column-width="1.15in" />
                    <fo:table-column
                        column-number="3"
                        column-width="1.15in" />
                    <fo:table-column
                        column-number="4"
                        column-width="1.15in" />
                    <fo:table-column
                        column-number="5"
                        column-width="1.15in" />
                    <fo:table-body start-indent="0in">
                        <fo:table-row>
                            <fo:table-cell
                                background-color="#F2F2F2"
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in"
                                    text-align="center">
                                    <inline
                                        font-size="12.0pt"
                                        font-weight="bold">
                                        <inline font-family="PMingLiU">序號</inline>
                                    </inline>
                                </block>
                            </fo:table-cell>
                            <fo:table-cell
                                background-color="#F2F2F2"
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in"
                                    text-align="center">
                                    <inline
                                        font-size="12.0pt"
                                        font-weight="bold">
                                        <inline font-family="PMingLiU">項目名稱</inline>
                                    </inline>
                                </block>
                            </fo:table-cell>
                            <fo:table-cell
                                background-color="#F2F2F2"
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in"
                                    text-align="center">
                                    <inline
                                        font-size="12.0pt"
                                        font-weight="bold">
                                        <inline font-family="PMingLiU">結果</inline>
                                    </inline>
                                </block>
                            </fo:table-cell>
                            <fo:table-cell
                                background-color="#F2F2F2"
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in"
                                    text-align="center">
                                    <inline
                                        font-size="12.0pt"
                                        font-weight="bold">
                                        <inline font-family="PMingLiU">備註</inline>
                                    </inline>
                                </block>
                            </fo:table-cell>
                            <fo:table-cell
                                background-color="#F2F2F2"
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in"
                                    text-align="center">
                                    <inline
                                        font-size="12.0pt"
                                        font-weight="bold">
                                        <inline font-family="PMingLiU">其他</inline>
                                    </inline>
                                </block>
                            </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                            <fo:table-cell
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in">data</block>
                            </fo:table-cell>
                            <fo:table-cell
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in">data</block>
                            </fo:table-cell>
                            <fo:table-cell
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in">data</block>
                            </fo:table-cell>
                            <fo:table-cell
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in">data</block>
                            </fo:table-cell>
                            <fo:table-cell
                                border-bottom-color="#000000"
                                border-bottom-style="solid"
                                border-bottom-width="2.25pt"
                                border-left-color="#000000"
                                border-left-style="solid"
                                border-left-width="2.25pt"
                                border-right-color="#000000"
                                border-right-style="solid"
                                border-right-width="2.25pt"
                                border-top-color="#000000"
                                border-top-style="solid"
                                border-top-width="2.25pt"
                                padding-bottom="0mm"
                                padding-left="1.91mm"
                                padding-right="1.91mm"
                                padding-top="0mm">
                                <block
                                    font-size="12.0pt"
                                    line-height="100%"
                                    space-after="0in"
                                    space-before="0in">data</block>
                            </fo:table-cell>
                        </fo:table-row>
                    </fo:table-body>
                </fo:table>
            </block>
            <block font-size="12.0pt" />
        </flow>
    </page-sequence>
</root>